name: Pruebas unitarias
on:
  push:
    branches: 
    - 'Feature*'
jobs:
  job1:
    permissions: write-all
    name: Pruebas
    if: ${{ contains(github.event.head_commit.message, 'MERGE_MAIN') }}
    runs-on: ubuntu-latest
    steps:
    - name: Extrae el nombre de la rama
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: hace merge de main a la feature
      uses: devmasx/merge-branch@master
      with:
        type: now
        from_branch: main
        target_branch: ${{ steps.extract_branch.outputs.branch }}
        github_token: ${{ github.token }}
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.9.13'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s test
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Si pasa las pruebas hace merge
      if: ${{ success() }}
      env:
        MENSAJE_EXITO: Todas las pruebas fueron exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_EXITO}"
    
