name: Integrar con develop
on:
  push:
    branches: 
    - 'Feature*'
jobs:
  job1:
    permissions: write-all
    name: Integrar-Develop-Feature
    if: ${{ contains(github.event.head_commit.message, 'MERGE_MAIN') }}
    runs-on: ubuntu-latest
    steps:
    - name: hace merge de develop a la feature
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: master
        target-branch: ${{ github.ref }}
  job2: 
    needs: job1
    name: Pruebas-unitarias
    runs-on: ubuntu-latest
    steps:
    - name: Checkout de repositorio
      uses: actions/checkout@v2
    - name: Configuración de entorno de python
      uses: actions/setup-python@v2
      with:
          python-version: '3.9.13'
    - name: Instalación de librerías y dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Correr pruebas
      id: correr-pruebas
      run: python -m unittest discover -s test
    - name: Validar resultado con errores
      if: ${{ failure() }}
      env:
        MENSAJE_ERROR: Una o varias pruebas fallaron
      run: echo "::set-output name=respuesta::${MENSAJE_ERROR}"
    - name: Si pasa las pruebas hace merge
      if: ${{ success() }}
      env:
        MENSAJE_SUCCESS: Pruebas exitosas
      run: echo "::set-output name=respuesta::${MENSAJE_SUCCESS}"
  job3: 
    needs: job2
    name: Integrar-Feature-Develop
    runs-on: ubuntu-latest
    steps:
    - name: 'Integrando feature a develop'
      uses: tukasz/direct-merge-action@master
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        source-branch: ${{ github.ref }}
        target-branch: master
    
